<?php
namespace DevelSuite\mail;

use DevelSuite\config\dsConfig;

class dsMailerTest extends \PHPUnit_Framework_TestCase {
	public function setUp() {
		// transporttypes available: smtp, sendmail, mail
		dsConfig::write('mailing.default.sender', array("info@develman.de" => "Develman.de"));
		dsConfig::write('mailing.transport', "smtp");
		dsConfig::write('mailing.smtp.hostname', "smtp.develman.de");
		dsConfig::write('mailing.smtp.username', "m0228c6e");
		dsConfig::write('mailing.smtp.password', "3#bofh7g");
	}

	public function testSendmail() {
		$message = \Swift_Message::newInstance("Test - DevelSuite");
		$message->setTo("georg@develman.de");

		$message->setBody("<html><body></body>This is a testmail generated by the dsMailerTest of th DevelSuite MVC-Framework</body></html>", "text/html");
		$message->addPart("This is a testmail generated by the dsMailerTest of th DevelSuite MVC-Framework", "text/plain");

		$mailer = new dsMailer();
		$mailer->setMessage($message);
		$this->assertGreaterThan(0, $mailer->send());
	}
}